= Applied Graph Algorithms Training

Welcome to the Neo4j Graph Algorithms Online Training Course!

== Course Outline

Graph algorithms are used to compute metrics for graphs, nodes, or relationships.
They can provide insights on relevant entities (centralities, ranking) in the graph or inherent structures such as communities (community-detection, graph-partitioning, clustering).
In this course you will learn how to use Neo4j's Graph Algorithms library to enhance your graph based applications.

== Pre Requisites

* Completed Intro to Neo4j training or have equal Cypher proficiency
* Familiar with the concept of a web application

== Yelp Dataset

https://www.yelp.com/[Yelp^] helps people find local businesses based on reviews, preferences, and recommendations.
Over 163 million reviews have been written on the platform as of the middle of 2018.
Yelp has been running the Yelp Dataset challenge 2 since 2013, a competition that encourages people to explore and research Yelp’s open dataset.

As of Round 12 of the challenge, the open dataset contained:

* Over 7 million reviews plus tips
* Over 1.5 million users and 280,000 pictures
* Over 188,000 businesses with 1.4 million attributes
* 10 metropolitan areas

The https://www.yelp.com/dataset/challenge[Yelp dataset^] represents real data that is very well structured and highly interconnected.
It’s a great showcase for graph algorithms that you can also download and explore.

*Put something here for them to click through so we can approve the use of the dataset*

We'll be using Neo4j Browser guides to help us work through this course. These guides allow us to embed content and Cypher queries in Neo4j Browser. Once you've created your Neo4j Sandbox instance, open the first guide running following command into the query pane of the Neo4j Browser:

[source,cypher]
----
:play https://guides.neo4j.com/sandbox/applied_graph_algorithms/01_cypher_overview
----

Work through the guide to see how to use Cypher to explore the dataset. When you've completed it, pick up in this document where you left off.

Now that we're familiar with the data, let's have a brief overview of graph algorithms and what we can do with them.

== Graph Algorithms

We have 4 types of graph algorithms:

* Path Finding
* Centrality
* Community Detection
* Similarity

The first 3 are classic graph algorithms and the 4th can be used on its own or in combination with the other 3.

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/11qo8dmLzH4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Building our own yelp.com

We're going to build our own version of yelp.com using this data.
We'll use graph algorithms to improve the quality of results in our application.

The rest of the course will follow this structure:

* Introduction to an algorithm
* Learn how to execute the algorithm
* Use the results to improve

Before we continue, open the CodeSandbox link below in another tab.
This CodeSandbox contains all the code for the application that we'll be building.

https://codesandbox.io/embed/github/neo4j-contrib/applied-graph-algorithms-training/tree/master/react-app[Launch CodeSandbox^]

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/NK3yC1cSlVU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Part 1: Category Hierarchy

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/Urb6RcpOL_c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

In this section we're going to navigate business categories.
Let's first have a look at the part of the application that we're going to build.

Open the first tab on the CodeSandbox application that you opened in the previous section.
You should be on this screen:

*printscreen of the page*

At the moment we have a list of 100 random categories, and making sense of the data isn't easy.
One way that we could make things easier for our user is if we let them navigate a taxonomy of categories.

Copy the following command into the query pane of the Neo4j Browser and execute it:

[source, cypher]
----
:play https://guides.neo4j.com/sandbox/applied_graph_algorithms/02_category_hierarchy
----

== Part 2: Ordering search results

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/mYEGxMScovM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

In this section we're going to improve the display of search results.
Let's have  a look at the part of the application that we're going to build.

Open the second tab on the CodeSandbox application.
You should be on this screen:

*printscreen here*

Copy the following command into the query pane of the Neo4j Browser and execute it:

[source, cypher]
----
:play https://guides.neo4j.com/sandbox/applied_graph_algorithms/03_search_results
----


Now let's update the application to use this new information.
Instead of selecting the reviews for our businesses based on the opinions of users unrelated to `user-name`, we'll show reviews written by similar users.

== Part 3: Most relevant reviews

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/jztUXGRazvY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

In this section we'll learn how to use the Personalized PageRank algorithm to return relevant businesses in search results.


Copy the following command into the query pane of the Neo4j Browser and execute it:

[source, cypher]
----
:play https://guides.neo4j.com/sandbox/applied_graph_algorithms/04_relevant_reviews
----

== Part 4: Photo based gallery recomendations

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/m0GrcuM8yvg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

In this section we'll learn how to use the Label Propagation algorithm to recommend photos.


Copy the following command into the query pane of the Neo4j Browser and execute it:

[source, cypher]
----
:play https://guides.neo4j.com/sandbox/applied_graph_algorithms/04_relevant_reviews
----
