= Applied Graph Algorithms Training

== Applied Graph Algorithms Training

Welcome to the Neo4j Graph Algorithms Online Training Course!

Graph algorithms are used to compute metrics for graphs, nodes, or relationships.
They can provide insights on relevant entities (centralities, ranking) in the graph or inherent structures such as communities (community-detection, graph-partitioning, clustering).
In this course you will learn how to use Neo4j's Graph Algorithms library to enhance your graph based applications.

== Yelp Dataset

https://www.yelp.com/[Yelp^] helps people find local businesses based on reviews, preferences, and recommendations.
Over 163 million reviews have been written on the platform as of the middle of 2018.
Yelp has been running the Yelp Dataset challenge 2 since 2013, a competition that encourages people to explore and research Yelp’s open dataset.

As of Round 12 of the challenge, the open dataset contained:

* Over 7 million reviews plus tips
* Over 1.5 million users and 280,000 pictures
* Over 188,000 businesses with 1.4 million attributes
* 10 metropolitan areas

The https://www.yelp.com/dataset/challenge[Yelp dataset^] represents real data that is very well structured and highly interconnected.
It’s a great showcase for graph algorithms that you can also download and explore.

*Put something here for them to click through so we can approve the use of the dataset*

== Graph Model

This is the graph model that we'll be working with:

image::images/yelp.svg[]

== Cypher Refresher

Cypher is a graph query language that we'll be using in this tutorial.
Let's do some exploratory analysis to get a feel for the data.

== Cypher Refresher: Cities

We'll start by seeing which cities have the most reviews:

[source,cypher]
----
include::queries.cql[tag=most-reviewed-cities]
----

Las Vegas, Phoenix, and Toronto have the majority of reviews so we'll use one of those so that we have plenty of data to work with.
We'll use Phoenix because $REASONS.

== Cypher Refresher: Most Reviewed Restaurants

We can find the most reviewed restaurants in Phoenix by executing the following query:

[source,cypher]
----
include::queries.cql[tag=most-reviewed-restaurants]
----

== Cypher Refresher: Interesting People

And who are some interesting people?

[source,cypher]
----
include::queries.cql[tag=interesting-reviewers]
----

Let's store some of those interesting users for later.
Run the following query to store them in the `userIds` parameter:

[source,cypher]
----
include::queries.cql[tag=userids]
----

== Cypher Refresher: Interesting People

We can run the following query to see some of the reviews that these people have written:

[source,cypher]
----
include::queries.cql[tag=selected-users]
----

Now that we're familiar with the data we're going to build our own Yelp application based on it.

== Graph Algorithms

We have 4 types of graph algorithms:

* Path Finding
* Centrality
* Community Detection
* Similarity

The first 3 are classic graph algorithms and the 4th can be used on its own or in combination with the other 3.

== Part 1: Category Hierarchy

In this section we'll learn how to use the Overlap Similarity algorithm to navigate categories.

We start with a list of 100 random categories but no relationships between them.

Now let's run the algorithm:

[source,cypher]
----
include::queries.cql[tag=compute-taxonomy-template]
----

And this is the answer:

[source,cypher]
----
include::queries.cql[tag=compute-taxonomy]
----

Now let's remove any transitive relationships that the algorithm's created.
Run the following query:

[source,cypher]
----
include::queries.cql[tag=transitive-taxonomy]
----

Now that we've computed relationships between categories, let's update the application to only return top level categories.

NOTE: Top level categories don't have an outgoing `NARROWER_THAN` relationship.

== Part 2: Ordering search results

In this section we'll learn how to use the Pearson Similarity algorithm to recommend reviews based on user similarity.

[source,cypher]
----
include::queries.cql[tag=topk-similar-users-template]
----

And here's the answer:

[source,cypher]
----
include::queries.cql[tag=topk-similar-users]
----

We want to use this similarity graph to improve the reviews that we show on our application.
We can find similar users by following the `SIMILAR` relationship from a user:

[source,cypher]
----
include::queries.cql[tag=find-topk-similar-users]
----

Now let's update the application to use this new information.
Instead of selecting the reviews for our businesses based on the opinions of users unrelated to `user-name`, we'll show reviews written by similar users.

== Part 3: Most relevant reviews

In this section we'll learn how to use the Personalized PageRank algorithm to return relevant businesses in search results.

== Part 4: Photo based gallery recomendations

In this section we'll learn how to use the Label Propagation algorithm to recommend photos.
