== Quiz Questions for Applied Graph Algorithms Training


=== Quiz Part 1: Category Hierarchy Video

==== Algorithm Understanding: Overlap Similarity

Which of the following best describe what the Overlap Similarity algorithm computes?

Answers:

* the size of the intersection divided by the size of the smaller of the two sets
* the number of pairwise disagreements between two ranking lists
* the size of the intersection divided by the size of the union of two sets
* the minimum number of operations required to transform one string into the other

Correct Answer:

* the size of the intersection divided by the size of the smaller of the two sets

==== Matching Results

Which of these categories are top level categories i.e. they don't have any outgoing `NARROWER_THAN` relationships?

Answers:

* Shopping
* Wine Bars
* Doctors
* Local Flavor

Correct Answer:

* Shopping
* Local Flavor

==== Expectation Check
Question:

Answers:
* Blah
* Blah

=== Quiz Part 2: Ordering search results

==== Algorithm Understanding: Pearson Similarity

Which of the following are valid values that can be returned by the Pearson Similarity algorithm?

Answers:

* 0.72
* -3.41
* 2.34
* -0.52

Correct Answer:

* 0.72
* -0.52

==== Matching Results

Question:

Answers:
* Blah
* Blah

Correct Answer:

==== Expectation Check
Question:

Answers:
* Blah
* Blah

=== Quiz Part 3: Most relevant reviews

==== Algorithm Understanding: Personalized PR

Which of the following best describe the Personalized PageRank algorithm?

Answers:

* It measures similarity of the structural context in which objects occur, based on their relationships with other objects.
* It's a variation of the PageRank algorithm that is biased towards a set of source nodes
* It computes the influence of a node by measuring the number of the immediate neighbors and also all other nodes in the network that connect to the node under consideration through these immediate neighbors
* It's a variation of the PageRank algorithm that reduces the bias that PageRank has towards assigning higher scores to nodes with relationships from nodes that have few outgoing relationships.

Correct Answer:

* It's a variation of the PageRank algorithm that is biased towards a set of source nodes


==== Matching Results
Question:

Answers:
* Blah
* Blah

Correct Answer:

==== Expectation Check
Question:

Answers:
* Blah
* Blah

=== Quiz Part 4: Photo based gallery recomendations

==== Algorithm Understanding: LPA

Which voting mechanism does Neo4j's Label Propagation algorithm use?

Answers:

* Random Walk Method
* Pull Method
* Push Method
* Modularity Optimization Method


Correct Answer:

* Pull Method

==== Matching Results
Question:

Answers:
* Blah
* Blah

Correct Answer:

==== Expectation Check
Question:

Answers:
* Blah
* Blah

==== Course Expectation Check
Question:

Answers:
* Blah
* Blah
