== Video Scripts for Applied Graph Algorithms Training

=== Intro Video (TBD - Will create at the end, if we think it's needed)

==== Goals
==== Algorithm Buckets (Do we want to cover this?)
==== Structure of Training
==== Getting Help

=== Part 1: Category Hierarchy Video
* Now that we've explored the Yelp data a bit, we're going to take a deeper look at business categories. 

==== Problem Situation
[Screenshot from the first category example]
* Some of you may have noticed that there are many business categories in Yelp that seem related but aren't organized together. For example, we can safely assume some similar menu items or food styles between a business categorized as a sushi bar and another one as a ramen shop.
[Visual of sushi - ramen]
* We can imagine how being able to group similar businesses is essential to certain types of analysis such as finding general preferences. But it's also essential for creating intuitive navigation between types of business. 
* Our challenge in this section is to take a list of a 100 random business categories and automatically create a taxonomy that's easier for users to traverse.
[Screenshot from the first category example with "100" and steps]
* Since it would be tedious to do this manually on even a small dataset, we want to learn the structure and hierarchy of business categories that are already hiding in the Yelp data, using a graph algorithm.

==== Algorithm: Overlap Similarity
* The Overlap Similarity algorithm is the perfect choice when we're trying to find the hierarchy in data and develop super and sub-categories. This is related to how it measures the overlap between two groups of nodes.  
* The algorithm provides a similarity coefficient that represents the co-occurrence of items between those groups. 
[Visual of the Formula with A and B]
* Mathematically, the coefficient is defined as the intersection divided by the smaller of the two groups.  
[Visual of the circles - animate below]
* For example, if set A contains {Orange, Blue, Green} and set B contains {Orange, Blue, Purple, Black} then the overlap algorithm counts 2 co-occurrences {Cyan, Blue} and divides that count by the number of items in the smallest set, in this case, 3.  The resulting overlap coefficient is 2/3 which is 0.66.
* If A contains {Orange, Blue, PURPLE} then the overlap coefficient would be 1.
* A coefficient of 1 indicates that either the groups are identical or more likely, that one is a subgroup of the other. 
[Visual of the circles but now completely overlap. Animate?]
* Although the Overlap Similarity algorithm is also used to evaluate general similarities its use of the smaller set as a denominator makes its ideal for extracting subgroups. 
** Identification of multiple subgroups is an effective way to develop taxonomies.  

==== Tips / Warnings?
* During the excercise, you may find bla blah [Mark / Will? Maybe we add once we're almost done.] 
* If you get stuck, you can always refer to our documentation:
** On the developers guide - https://neo4j.com/docs/developer-manual/current/ 
** On the Overlap Similarity Algorithm - https://neo4j.com/docs/graph-algorithms/3.4/algorithms/similarity-overlap/
* Also, please feel free to ask for help on our Community Forum https://community.neo4j.com/c/general/online-training 

==== At The End of This Part
* By the end of this section we will have updated the user navigation to reflect top-level categorizations of Yelp businesses.
* There will be a short quiz to evalute progress.
* You should be able to explain what the overlap coefficient represents and be familiar with using a NARROWER_THAN relationship to build a taxonomy.


=== Part 2: Ordering search results
* Now that we've have a good navigation for users that next thing we'd like to do is show more relevant information to our users.

==== Problem Situation
* Like so many reviews sites, there is a lot of information in Yelp to sift through. It would be best to develop a way to show users information that's most relevant to them personally.
* For example, instead of selecting the reviews for businesses based on the opinions of reviwers unrelated to the users, we want to show reviews written by someone similar. 
* Our challenge in this section is to order reviews in a search result by the reviewers most like the user. Then we'll update the application to use this new information.

==== Algorithm: Pearson Smiliarity
* The Pearson Smiliarity algorithm is widely used in the sciences and is particularly well-suited for recommendations based on user ratings because it takes into account the fact that different users will have different mean ratings.
** On average some users will tend to give higher ratings than others. 
** Since Pearson similarity considers differences about the mean, this metric will account for these discrepancies.
* The algorithm provides a similarity correlation coefficient with is the measure of the linear correlation between two variables X and Y. 
* It has a value between +1 and −1, where 1 is total positive linear correlation, 0 is no linear correlation, and −1 is total negative linear correlation. 

WIP




==== Tips / Warnings?  
==== At The End of This Part
You should be able to...
There will be a quiz.

=== Part 3: Most relevant reviews

==== Problem Situation
==== Algorithm: LPA
==== Tips / Warnings? 
==== At The End of This Part
You should be able to...
There will be a quiz.

=== Part 4: Photo based gallery recomendations

==== Problem Situation
==== Algorithm: PPR
==== Tips / Warnings? 
==== At The End of This Part
You should be able to...
There will be a quiz.
